### ISSUE TITLE
"Emoji Version 14.0" is not unemojified

### ISSUE THREAD

**Issue by chachagogogo** [omnidan/node-emoji#121] opened 2023-01-12 03:57 UTC
```
  console.log('test1', emoji.unemojify('😍test1'));
  console.log('test2', emoji.unemojify('🫥test2'));

// test1 :heart_eyes:test1
// test2 🫥test2
````

I'd checked several emojis and found out that [Emoji Version 14.0](https://emojipedia.org/emoji-14.0/) is not unemojified.

Thank you.

**Comment by JoshuaKGoldberg** [comment] 2023-05-20 16:00
Marking this as a duplicate of #132. In v2 this library switched to using [`emojilib`](https://github.com/muan/emojilib) as the source of truth for emoji.

**Closed by JoshuaKGoldberg** 2023-05-20 16:00 UTC
