### ISSUE TITLE
1.4.2 release is missing index.js

### ISSUE THREAD

**Issue by cdpuk** [omnidan/node-emoji#29] opened 2016-12-02 14:34 UTC
Bumped in to this just a moment ago when 1.4.2 was released, as the popular Yarn package management tool depends on this, and was not tied to a specific version.

```
# npm install node-emoji@1.4.1
...
└── node-emoji@1.4.1  extraneous
# ls -l node_modules/node-emoji/index.js
-rw-r--r-- 1 user user 40 Feb 28  2016 node_modules/node-emoji/index.js

# npm install node-emoji@1.4.2
...
└── node-emoji@1.4.2  extraneous
# ls -l node_modules/node-emoji/index.js
ls: cannot access 'node_modules/node-emoji/index.js': No such file or directory
```

Not an expert on how packages work, but I assume this is needed in order to `require` a package.

**Comment by omnidan** [comment] 2016-12-02 14:42
@cdpuk the `require` call should read the `main` property in `package.json`, which is set to `lib/emoji.js`, so everything should still work fine. I even tried this myself and `node-emoji` still works as expected with 1.4.2 :grin: let me know if this causes any issues for you.

**Comment by kevynb** [comment] 2016-12-02 14:43
Hello,

I have the same problem as cdpuk, seems it's not reading the package.json :/

**Comment by omnidan** [comment] 2016-12-02 14:43
@kevynb can you let me know what the issue is and how to reproduce it?

**Comment by omnidan** [comment] 2016-12-02 14:46
I just tried installing with npm (via `npm install node-emoji`) and yarn (via `yarn add node-emoji`), then executed the code from README:

```js
var emoji = require('node-emoji')
emoji.get('coffee') // returns the emoji code for coffee (displays emoji on terminals that support it)
emoji.which(emoji.get('coffee')) // returns the string "coffee"
emoji.get(':fast_forward:') // `.get` also supports github flavored markdown emoji (http://www.emoji-cheat-sheet.com/)
emoji.emojify('I :heart: :coffee:!') // replaces all :emoji: with the actual emoji, in this case: returns "I ❤️ ☕️!"
emoji.random() // returns a random emoji + key, e.g. `{ emoji: '❤️', key: 'heart' }`
```

and everything works fine.

**Comment by kevynb** [comment] 2016-12-02 14:47
Yep.

I did an `npm install yarn@0.17.8`
then `yarn`

which gave me:
```
14:38:50.327 - Run 'yarn'
14:38:50.541 /XXXXX/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/bin/yarn.js:62
14:38:50.542       throw err;
14:38:50.542       ^
14:38:50.542 
14:38:50.542 Error: ENOENT: no such file or directory, open '/XXXXX/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/node_modules/node-emoji/index.js'
14:38:50.542     at Error (native)
14:38:50.542     at Object.fs.openSync (fs.js:640:18)
14:38:50.542     at Object.fs.readFileSync (fs.js:508:33)
14:38:50.542     at Object.Module._extensions..js (module.js:578:20)
14:38:50.542     at Module.load (module.js:487:32)
14:38:50.542     at tryModuleLoad (module.js:446:12)
14:38:50.542     at Function.Module._load (module.js:438:3)
14:38:50.542     at Module.require (module.js:497:17)
14:38:50.542     at require (internal/module.js:20:19)
14:38:50.543     at Object.<anonymous> (/XXXXXX/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/lib/cli/commands/install.js:199:15)
```

**Comment by omnidan** [comment] 2016-12-02 14:49
@kevynb `yarn` is specific to your project, can you create a minimal project on github (or just upload a `package.json`), so I can reproduce this?

**Comment by omnidan** [comment] 2016-12-02 14:50
I tried it with my own `package.json`:

```js
{
  "dependencies": {
    "node-emoji": "^1.4.2"
  }
}
```

Then ran `yarn`, and everything works fine for me :/

**Comment by omnidan** [comment] 2016-12-02 14:52
I tried it with the latest `yarn` version (0.17.10) and your version (0.17.8) - both work fine, not sure how to reproduce this issue.

**Comment by pdhoopr** [comment] 2016-12-02 14:55
There are open issues with Yarn about this. I recently opened [#2119](https://github.com/yarnpkg/yarn/issues/2119), but the issue [#2072](https://github.com/yarnpkg/yarn/issues/2072) is definitely related and has more conversation around it.

**Comment by omnidan** [comment] 2016-12-02 14:58
@pdhoopr I see, seems like this is an issue related to the yarn cache. In that case, I'll close this issue, as it doesn't seem to be related to node-emoji. Thanks for all the comments, and feel free to reopen if you find out anything new :smile:

**Comment by kevynb** [comment] 2016-12-02 14:59
I reproduce it on one machine but not the other. Trying to spot how it happens

**Closed by omnidan** 2016-12-02 14:58 UTC

**Comment by omnidan** [comment] 2016-12-02 15:04
@kevynb no problem :smile: let me know if there's any news :wink:

**Comment by mandragorn** [comment] 2016-12-02 15:07
I'm getting the same problem, trying to figure out if I can fix it by clearing out yarn stuff.

**Comment by omnidan** [comment] 2016-12-02 15:08
@mandragorn try uninstalling and reinstalling yarn, maybe clearing the yarn cache

**Comment by mandragorn** [comment] 2016-12-02 15:15
Its happening for builds that install yarn fresh (new continuous integration servers).  Upgrading to yarn 0.17.10 fixes it.

**Comment by pdhoopr** [comment] 2016-12-02 15:33
Clearing the Yarn cache does seem to be the solution here. OS-specific cache folders can be found in Yarn issue [#2119](https://github.com/yarnpkg/yarn/issues/2119).

**Comment by wjordan** [comment] 2016-12-02 21:29
@omnidan this entry-point change is an incompatible API change that breaks [Semantic Versioning](http://semver.org/) guidelines, which npm [recommends](https://docs.npmjs.com/getting-started/semantic-versioning) for packages published to its repository. This breaking change should trigger a MAJOR version bump, otherwise it will continue to break downstream dependencies.

As far as I'm concerned, this issue is unresolved and will continue to cause dependency issues for any version of `yarn` installed via npm (because it depends on a major-version-pinned [`"node-emoji": "^1.0.4"`](https://github.com/yarnpkg/yarn/blob/fa16b8b2c6ee34a15b9fd5370600a6dd6a67d4c7/package.json#L28) in its `package.json`) until a new PATCH or MINOR version of `node-emoji` (`1.4.3` or `1.5.0`) is published that reverts major-version `1.x` of this library to its original API behavior.

To follow-up, a MAJOR version of `node-emoji` (`2.0.0`) could be published with this API-breaking change without causing further issues.

**Comment by omnidan** [comment] 2016-12-02 21:33
@wjordan Thanks for the information! I released `1.4.3` reverting the changes in `1.4.2` and moved them to a `2.0` branch. Let me know if it works fine now.

**Comment by pdhoopr** [comment] 2016-12-02 21:59
@wjordan @omnidan It's worth noting that an entry point change is not viewed by everyone as an incompatible API change. The conversation around [this `node-uuid` issue](https://github.com/kelektiv/node-uuid/issues/163) is a good example.

The relevant point here is that this package still worked the same once the entry point was changed in `v1.4.2` as it did in the previous `v1.4.1`. So if you wanted to download it and use it directly like in the docs...

```js
var emoji = require('node-emoji')
emoji.get('coffee')
```

...that code worked exactly the same before and after the entry point change, and nothing else in the public API was modified, so the minor version bump was probably fine. In the end, I guess it's up to the discretion of the library author in cases like this. 

Ultimately though, the real problem here was with Yarn caching... a major version bump just happens to be a workaround.

**Comment by omnidan** [comment] 2016-12-02 22:01
@pdhoopr yes this is definitely an issue with yarn caching, but it's also not such an important change that it has to be released now. I'll keep this reverted until yarn fixes the issue. :wink: Thanks for all the comments!

**Comment by wjordan** [comment] 2016-12-03 10:14
@omnidan Excellent! Thanks for the super-quick response and release. The updated version did fix the issue in my build and unblocked my team quickly.

After looking into the issue further, it does seem that you're correct that this is a bug in Yarn's require-resolving cache that didn't respect package-dependency updates, and nothing to do with breaking semantic versioning in a strict sense. Sorry for the false alarm but I do appreciate the quick patch release nonetheless, and I'm sure you've helped save many others out there many hours of pain with that.
