### ISSUE TITLE
Some emojis are not supported.

### ISSUE THREAD

**Issue by seongjin605** [omnidan/node-emoji#92] opened 2020-07-10 04:49 UTC
# example
❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 ❣️ 💕 💞 💓 💗 💖 💘 💝 💟 ☮️ ✝️ ☪️ 🕉 ☸️ ✡️ 🔯 🕎 ☯️ ☦️ 🛐 ⛎ ♈️ ♉️ ♊️ ♋️ ♌️ ♍️ ♎️ ♏️ ♐️ ♑️ ♒️ ♓️ 🆔 ⚛️ 🉑 ☢️ ☣️ 📴 📳 🈶 🈚️ 🈸 🈺 🈷️ ✴️ 🆚 💮 🉐 ㊙️ ㊗️ 🈴 🈵 🈹 🈲 🅰️ 🅱️ 🆎 🆑 🅾️ 🆘 ❌ ⭕️ 🛑 ⛔️ 📛 🚫 💯 💢 ♨️ 🚷 🚯 🚳 🚱 🔞 📵 🚭 ❗️ ❕ ❓ ❔ ‼️ ⁉️ 🔅 🔆 〽️ ⚠️ 🚸 🔱 ⚜️ 🔰 ♻️ ✅ 🈯️ 💹 ❇️ ✳️ ❎ 🚗 🚕 🚙 🚌 🚎 🏎 🚓 🚑 🚒 🚐 🚚 🚛 🚜 🦯 🦽 🦼 🛴 🚲 🛵 🏍 🛺 🚨 🚔 🚍 🚘 🚖 🚡 🚠 🚟 🚃 🚋 🚞 🚝 🚄 🚅 🚈 🚂 🚆 🚇 🚊 🚉 ✈️ 🛫 🛬 🛩 💺 🛰 🚀 

# result
![image](https://user-images.githubusercontent.com/16683075/87117611-f430e100-c2b3-11ea-8906-62c240025f8d.png)

**How can i solve it?**

**Comment by francescov1** [comment] 2021-03-26 17:19
🥳 as well, seems like a popular one that should be here

**Comment by JoshuaKGoldberg** [comment] 2023-05-20 15:56
#113 brought in [`emojilib`](https://github.com/muan/emojilib) as the source of truth for emojis. And #132 is looking into bumping to the latest version of `emojilib`. So this is likely a duplicate of that work. Cheers!

**Closed by JoshuaKGoldberg** 2023-05-20 15:56 UTC
